const PMETA={
 compute:{e:'🖥️',s:'the substrate'},
 openai:{e:'🌀',s:'AGI, eventually'},
 anthropic:{e:'🧭',s:'helpful, harmless, honest'},
 deepmind:{e:'♟️',s:'the bitter lesson'},
 xai:{e:'🚀',s:'maximum truth-seeking'},
 metallama:{e:'🦙',s:'superintelligence, personally'},
 mistral:{e:'🌬️',s:'European sovereignty'},
 deepseek:{e:'🐋',s:'efficiency'},
 qwen:{e:'☁️',s:'the everything cloud'},
 kimi:{e:'🌙',s:'the open frontier'},
 venice:{e:'🎭',s:'private inference'},
 localllama:{e:'🏠',s:'weights on your own disk',note:"the map-maker's tent"},
 vibecoding:{e:'✨',s:'the vibe'},
 agents:{e:'🤖',s:'autonomy'},
 genmedia:{e:'🎬',s:'the dream machine'},
 robotics:{e:'🦾',s:'embodiment'},
 aisafety:{e:'⏸️',s:'p(doom)'},
 eacc:{e:'⚡',s:'thermodynamic destiny'}
};
const PAPER=[
 ['compute','the water — everything floats on GPUs'],
 ['deepmind','$3.99T — Alphabet, its parent'],
 ['metallama','$1.50T — Meta, its parent'],
 ['anthropic','$965B Series H, IPO filed'],
 ['openai','$852B post-money, IPO ahead'],
 ['qwen','$270B — Alibaba, its parent'],
 ['xai','$230B Series E'],
 ['vibecoding','$60B — what SpaceX paid for Cursor'],
 ['deepseek','$52B, funding paused on purpose'],
 ['robotics','$39B — Figure, the fleet at BMW'],
 ['aisafety','$32B — SSI, zero product, on purpose'],
 ['kimi','$31.5B, chasing $50B pre-IPO'],
 ['mistral','$23B, Europe\'s one frontier lab'],
 ['genmedia','$5.4B — Suno, mid-lawsuit'],
 ['agents','$4B ARR — Cursor, the flagship agent'],
 ['venice','$1B and actually profitable'],
 ['localllama','no cap table — 780k runners of local weights'],
 ['eacc','$14.1M seed and a memeplex']
];
