const PMETA={
 fiat:{e:'🌊',s:'the unit of account'},
 btcmaxis:{e:'🟠',s:'sound money'},
 stablecoins:{e:'💵',s:'the digital dollar'},
 ethereum:{e:'💎',s:'credible neutrality'},
 exchangetokens:{e:'♠️',s:'the house'},
 xrparmy:{e:'💸',s:'the standard'},
 rwa:{e:'🏦',s:'the tokenized ledger'},
 solana:{e:'☀️',s:'speed'},
 memecoins:{e:'🐸',s:'attention'},
 privacy:{e:'🕵️',s:'the unseen ledger'},
 degenperps:{e:'🎰',s:'leverage'},
 hyperliquid:{e:'💧',s:'the onchain orderbook'},
 regens:{e:'🌻',s:'the commons',note:"the map-maker's tent"},
 nft:{e:'🖼️',s:'ownership'},
 artists:{e:'🎨',s:'the work itself'},
 daos:{e:'🗳️',s:'the community'},
 predictionmarkets:{e:'🎲',s:'calibration'},
 base:{e:'🔵',s:'the onramp'},
 brokerchains:{e:'🏹',s:'the onboarding funnel'},
 memedaos:{e:'🍕',s:'the bit, taken seriously'},
 restakers:{e:'♻️',s:'stacked yield'},
 zkpurists:{e:'🔐',s:'the proof'},
 mevsearchers:{e:'🌲',s:'the invisible auction'},
 airdropfarmers:{e:'🪂',s:'the snapshot'},
 ghostchains:{e:'🏚️',s:'what remains'},
 desci:{e:'🧫',s:'open science'},
 ordinals:{e:'🧿',s:'the inscription'},
 depin:{e:'📡',s:'the crowd-built grid'},
 oldguard:{e:'🏛️',s:'the roadmap'},
 aicoins:{e:'🤖',s:'open intelligence'},
 defi:{e:'⚙️',s:'permissionless finance'},
 linkmarines:{e:'🔗',s:'the truth feed'},
 trumpcoins:{e:'🎩',s:'the family business'},
 newl1s:{e:'🚄',s:'throughput'},
 l2s:{e:'🧅',s:'layered blockspace'}
};
const PAPER=[
 ['fiat','the water — all of it prices in dollars'],
 ['btcmaxis','$1287.9B across 3 coins'],
 ['stablecoins','$296.1B across 19 coins'],
 ['ethereum','$230.8B across 1 coin'],
 ['exchangetokens','$101.0B across 10 coins'],
 ['xrparmy','$72.5B across 3 coins'],
 ['rwa','$58.9B across 19 coins'],
 ['oldguard','$45.1B across 9 coins'],
 ['solana','$43.6B across 2 coins'],
 ['memecoins','$17.8B across 6 coins'],
 ['privacy','$14.9B across 3 coins'],
 ['hyperliquid','$12.3B across 1 coin'],
 ['defi','$9.9B across 7 coins'],
 ['newl1s','$8.9B across 5 coins'],
 ['aicoins','$7.3B across 6 coins'],
 ['trumpcoins','$6.2B across 3 coins'],
 ['linkmarines','$6.2B across 1 coin'],
 ['l2s','$2.8B across 4 coins'],
 ['degenperps','$2.3B across 2 coins'],
 ['nft','$1.0B across 6 coins'],
 ['base','$843M across 3 coins'],
 ['restakers','$552M across 2 coins'],
 ['daos','$490M across 2 coins'],
 ['ghostchains','$386M across 3 coins'],
 ['zkpurists','$335M across 3 coins'],
 ['predictionmarkets','$283M across 1 coin'],
 ['depin','$182M across 3 coins'],
 ['desci','$83M across 2 coins'],
 ['ordinals','$60M across 1 coin'],
 ['artists','$55M across 3 coins'],
 ['regens','$46M across 3 coins — and the commons'],
 ['memedaos','no token, on purpose'],
 ['mevsearchers','no token — they take it in-flight'],
 ['airdropfarmers','no token of their own; they want yours'],
 ['brokerchains','no coin — the token is the stock']
];