const PMETA={
 ocean:{e:'🌊',s:'the institutions'},
 sports:{e:'🏟️',s:'the game'},
 islam:{e:'☪️',s:'the ummah'},
 christian:{e:'✝️',s:"God's created order"},
 china:{e:'🐉',s:'the civilization-state'},
 catholic:{e:'⛪',s:'the church eternal'},
 india:{e:'🕉️',s:'the eternal dharma-nation'},
 pentecostal:{e:'🕊️',s:'the spirit moving'},
 indigenous:{e:'🌎',s:'the living land'},
 manifestation:{e:'🔮',s:'the responsive universe'},
 astrology:{e:'✨',s:"the sky's timing"},
 conspiracy:{e:'🕳️',s:'the hidden truth'},
 stan:{e:'💜',s:'the idol'},
 hustle:{e:'💸',s:'the exit number'},
 maga:{e:'🦅',s:'the nation'},
 progleft:{e:'✊',s:'the marginalized'},
 establishment:{e:'🏛️',s:'the institutions'},
 finance:{e:'📈',s:'the market'},
 maha:{e:'🥩',s:'the body'},
 manosphere:{e:'🗿',s:'masculinity'},
 ufo:{e:'🛸',s:'the veil'},
 socialist:{e:'🌹',s:'the working class'},
 witchtok:{e:'🌙',s:'the old gods'},
 tradcaths:{e:'📿',s:'the old Mass'},
 postliberal:{e:'🙏',s:'god'},
 btc:{e:'🟠',s:'sound money'},
 wsb:{e:'🦍',s:'the trade'},
 degrowth:{e:'🌱',s:'the living earth'},
 longevity:{e:'🧬',s:'escape velocity'},
 nondual:{e:'🍄',s:'the medicine'},
 eth:{e:'💎',s:'credible neutrality'},
 defi:{e:'🏦',s:'open rails'},
 degens:{e:'🎰',s:'the pump'},
 indie:{e:'🛠️',s:'shipping'},
 refusal:{e:'📵',s:'presence'},
 ea:{e:'⚖️',s:'counterfactual impact'},
 rationalists:{e:'🧠',s:'the truth'},
 doomers:{e:'🛑',s:'our continuity'},
 progress:{e:'🏗️',s:'plenty'},
 hardtech:{e:'🚀',s:'the machine'},
 eacc:{e:'⚡',s:'technocapital'},
 tpot:{e:'🌀',s:'the vibe'},
 regens:{e:'🌻',s:'the garden',note:"the map-maker's tent"},
 pronatalists:{e:'👶',s:'the unborn billions'},
 nrx:{e:'👑',s:'order'},
 netstate:{e:'🏙️',s:'exit'},
 dacc:{e:'🛡️',s:'distributed power'},
 liminal:{e:'🧘',s:'the whole'},
 forecasters:{e:'🎲',s:'calibration'},
 georgists:{e:'🏞️',s:'the land'},
 metamodern:{e:'🌗',s:'development'},
 doomeroptimists:{e:'🏕️',s:'the local'},
 cryonics:{e:'❄️',s:'the pattern'},
 girardians:{e:'🐐',s:'the innocent scapegoat'},
 cozyweb:{e:'🕯️',s:'the small room'},
 landian:{e:'👾',s:'the process'},
 remilia:{e:'🎀',s:'the network'},
 nihilists:{e:'🌑',s:'nothing',note:'named as a hazard to navigation, not steelmanned'}
};
const PAPER=[
 ['ocean','most of the developed world, invisibly'],
 ['sports','billions of fans'],['islam','~2 billion'],['christian','~2 billion believers'],
 ['china','~1.4 billion, one civilization-state'],['catholic','~1.4 billion, one pope'],
 ['india','~1.1 billion claimed'],['pentecostal','~600 million, fastest-growing'],
 ['indigenous','hundreds of millions, oldest'],['manifestation','hundreds of millions in practice'],
 ['astrology','hundreds of millions'],['conspiracy','hundreds of millions, load-bearing'],
 ['stan','tens of millions, best logistics'],['hustle','tens of millions of subscribers'],
 ['maga','tens of millions — loudest inner tribe'],['progleft','tens of millions, past peak'],
 ['establishment','tens of millions'],['finance','tens of millions'],
 ['maha','tens of millions across both wings'],['manosphere','millions of men, plus their coaches'],
 ['ufo','millions of believers, small vanguard'],['socialist','millions, organized'],
 ['witchtok','millions on the moon calendar'],['tradcaths','millions'],['postliberal','millions, rising'],
 ['btc','millions of holders'],['wsb','millions of accounts'],
 ['degrowth','a movement of millions, quiet online'],['longevity','millions watching, thousands on protocol'],
 ['nondual','millions dosed, clinical vanguard small'],['eth','about a million'],
 ['defi','hundreds of thousands'],['degens','hundreds of thousands'],['indie','hundreds of thousands'],
 ['refusal','a growing congregation of the logged-off'],['ea','tens of thousands'],
 ['rationalists','tens of thousands'],['doomers','tens of thousands steering billions in compute'],
 ['progress','a policy class, loud beyond its size'],['hardtech','tens of thousands'],
 ['eacc','embers'],['tpot','a few thousand accounts, dense'],['regens','small, seeding'],
 ['pronatalists','small, spreadsheeted, rising'],['nrx','a few hundred posters, adjacent to power'],
 ['netstate','thousands, passports to spare'],['dacc','a few thousand builders holding keys'],
 ['liminal','small & steady, holding the whole'],['forecasters','thousands'],['georgists','thousands'],
 ['metamodern','thousands'],['doomeroptimists','thousands'],['cryonics','thousands'],
 ['girardians','thousands'],['cozyweb','thousands'],['landian','hundreds'],['remilia','hundreds'],
 ['nihilists','unnumbered, unclaimed']
];
